# Generated by Django 5.1.15 on 2026-04-25 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('rugby', 'Rugby'), ('baseball', 'Baseball'), ('volleyball', 'Volleyball'), ('hockey', 'Hockey'), ('swimming', 'Swimming'), ('athletics', 'Athletics'), ('cycling', 'Cycling'), ('other', 'Other')], default='football', max_length=30)),
            ],
            options={
                'verbose_name': 'division',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'season',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='team name')),
                ('short_name', models.CharField(blank=True, max_length=10)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('rugby', 'Rugby'), ('baseball', 'Baseball'), ('volleyball', 'Volleyball'), ('hockey', 'Hockey'), ('swimming', 'Swimming'), ('athletics', 'Athletics'), ('cycling', 'Cycling'), ('other', 'Other')], default='football', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('home_venue', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disbanded', 'Disbanded')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('colors', models.CharField(blank=True, help_text='Primary / secondary colors', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_teams', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='teams.division')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='teams.season')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='players.player')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='teams.team')),
            ],
            options={
                'verbose_name': 'roster entry',
                'verbose_name_plural': 'roster entries',
                'ordering': ['jersey_number', 'player__full_name'],
                'unique_together': {('team', 'player', 'season')},
            },
        ),
    ]
