# Generated by Django 5.1.15 on 2026-04-25 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('competition', models.CharField(blank=True, max_length=200)),
                ('referee', models.CharField(blank=True, max_length=100)),
                ('attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('match_report', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'fixture',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('rugby', 'Rugby'), ('baseball', 'Baseball'), ('volleyball', 'Volleyball'), ('hockey', 'Hockey'), ('swimming', 'Swimming'), ('athletics', 'Athletics'), ('cycling', 'Cycling'), ('other', 'Other')], default='football', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('prize_money', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'verbose_name': 'tournament',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('fixture', 'Fixture / Match'), ('training', 'Training Session'), ('tournament', 'Tournament'), ('meeting', 'Meeting'), ('other', 'Other')], default='fixture', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('opponent', models.CharField(blank=True, max_length=200)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('is_home', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
