# Generated by Django 5.2.13 on 2026-04-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranding',
            name='discord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubbranding',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubbranding',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubbranding',
            name='twitch',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
