# Generated by Django 5.1.15 on 2026-04-25 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contract_type', models.CharField(choices=[('player', 'Player Contract'), ('staff', 'Staff Contract'), ('sponsorship', 'Sponsorship Agreement'), ('vendor', 'Vendor Contract'), ('facility', 'Facility Lease'), ('other', 'Other')], max_length=20)),
                ('party_name', models.CharField(max_length=200)),
                ('party_email', models.EmailField(blank=True, max_length=254)),
                ('party_phone', models.CharField(blank=True, max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(choices=[('EUR', 'EUR €'), ('USD', 'USD $'), ('GBP', 'GBP £')], default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='draft', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_notice_days', models.PositiveSmallIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='players.player')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('performance', 'Performance Clause'), ('bonus', 'Bonus Clause'), ('penalty', 'Penalty Clause'), ('confidential', 'Confidentiality'), ('termination', 'Termination'), ('renewal', 'Renewal Option'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_key_clause', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
