# Generated by Django 5.1.15 on 2026-04-25 11:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('opponent', models.CharField(blank=True, max_length=200)),
                ('technical', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tactical', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('physical', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mental', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('overall', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('summary', models.TextField()),
                ('recommendation', models.CharField(choices=[('sign_now', 'Sign Now'), ('monitor', 'Monitor'), ('trial', 'Invite for Trial'), ('not_suitable', 'Not Suitable')], max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='scouting/reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_reports', to='players.player')),
                ('scout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scout report',
                'verbose_name_plural': 'scout reports',
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('current_club', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('contacted', 'Contacted'), ('trialing', 'On Trial'), ('signed', 'Signed'), ('rejected', 'Rejected')], default='prospect', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('contact_info', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='scouting/talents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_talents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'talent profile',
                'verbose_name_plural': 'talent profiles',
                'ordering': ['-rating', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='watchlists', to='players.player')),
                ('talents', models.ManyToManyField(blank=True, related_name='watchlists', to='scouting.talentprofile')),
            ],
            options={
                'verbose_name': 'watchlist',
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
