# Generated by Django 5.2.13 on 2026-04-27 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
        ('teams', '0002_add_club_fk'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(choices=[('4-4-2', '4-4-2'), ('4-3-3', '4-3-3'), ('4-2-3-1', '4-2-3-1'), ('3-5-2', '3-5-2'), ('5-3-2', '5-3-2'), ('4-1-4-1', '4-1-4-1'), ('3-4-3', '3-4-3')], default='4-4-2', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='tournaments.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='teams.team')),
            ],
            options={
                'verbose_name': 'lineup',
                'verbose_name_plural': 'lineups',
                'unique_together': {('match', 'team')},
            },
        ),
        migrations.CreateModel(
            name='LineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_slot', models.CharField(blank=True, max_length=10)),
                ('position_label', models.CharField(blank=True, max_length=20)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_substitute', models.BooleanField(default=False)),
                ('is_captain', models.BooleanField(default=False)),
                ('sub_order', models.PositiveSmallIntegerField(default=0)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='players.player')),
            ],
            options={
                'verbose_name': 'lineup player',
                'verbose_name_plural': 'lineup players',
                'ordering': ['is_substitute', 'sub_order'],
                'unique_together': {('lineup', 'player')},
            },
        ),
    ]
