# Generated by Django 5.2.13 on 2026-04-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_add_lineup_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='season',
            field=models.CharField(blank=True, help_text='e.g. 2026-27', max_length=20),
        ),
    ]
