# Generated by Django 5.1.15 on 2026-04-25 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=120)),
                ('body_part', models.CharField(choices=[('head', 'Head'), ('neck', 'Neck'), ('shoulder', 'Shoulder'), ('arm', 'Arm'), ('elbow', 'Elbow'), ('wrist', 'Wrist'), ('chest', 'Chest'), ('back', 'Back'), ('hip', 'Hip'), ('groin', 'Groin'), ('thigh', 'Thigh'), ('knee', 'Knee'), ('shin', 'Shin'), ('ankle', 'Ankle'), ('foot', 'Foot'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor (< 7 days)'), ('moderate', 'Moderate (1–4 weeks)'), ('severe', 'Severe (1–3 months)'), ('critical', 'Critical (3+ months)')], default='minor', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('recovering', 'Recovering'), ('recovered', 'Recovered')], default='active', max_length=20)),
                ('injury_date', models.DateField()),
                ('expected_recovery', models.DateField(blank=True, null=True)),
                ('actual_recovery', models.DateField(blank=True, null=True)),
                ('mechanism', models.CharField(blank=True, help_text='How the injury happened', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_injuries', to='players.player')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_injuries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Injuries',
                'ordering': ['-injury_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('physical', 'Physical Exam'), ('blood_test', 'Blood Test'), ('vaccination', 'Vaccination'), ('imaging', 'Imaging (X-ray/MRI/CT)'), ('prescription', 'Prescription'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('physician', models.CharField(blank=True, max_length=120)),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical/records/')),
                ('is_confidential', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='players.player')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_details', models.TextField()),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('physio_name', models.CharField(blank=True, max_length=120)),
                ('milestones', models.TextField(blank=True, help_text='Newline-separated milestones')),
                ('progress_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('injury', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plan', to='medical.injury')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('physio', 'Physiotherapy'), ('massage', 'Massage'), ('ice', 'Ice / Cold Therapy'), ('surgery', 'Surgery'), ('medication', 'Medication'), ('rest', 'Rest'), ('gym', 'Gym Rehabilitation'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('practitioner', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('next_session', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='medical.injury')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
