"""
ApexForge PDF generation — ReportLab helpers.

Every public function returns an HttpResponse with Content-Type application/pdf.
"""
import io
from datetime import date

from django.http import HttpResponse
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, KeepTogether,
)
# Note: Spacer is only used in story (not as table cells — ReportLab rejects that)

# ── Palette ───────────────────────────────────────────────────────────────────
GREEN        = colors.HexColor("#059669")
GREEN_DARK   = colors.HexColor("#047857")
GREEN_LIGHT  = colors.HexColor("#ecfdf5")
GREEN_ACCENT = colors.HexColor("#a7f3d0")
GRAY_900     = colors.HexColor("#111827")
GRAY_700     = colors.HexColor("#374151")
GRAY_500     = colors.HexColor("#6b7280")
GRAY_200     = colors.HexColor("#e5e7eb")
GRAY_50      = colors.HexColor("#f9fafb")
RED_BG       = colors.HexColor("#fee2e2")
RED_FG       = colors.HexColor("#991b1b")
AMBER_BG     = colors.HexColor("#fef3c7")
AMBER_FG     = colors.HexColor("#92400e")
BLUE_BG      = colors.HexColor("#dbeafe")
BLUE_FG      = colors.HexColor("#1e40af")
WHITE        = colors.white

PAGE_W, PAGE_H = A4
MARGIN  = 1.8 * cm
BODY_W  = PAGE_W - 2 * MARGIN          # ≈ 17.9 cm
BANNER_H = 1.7 * cm
TOP_MARGIN = MARGIN + BANNER_H + 0.5 * cm   # content starts below banner
BOT_MARGIN = MARGIN + 0.6 * cm             # content ends above footer


# ── Paragraph style factory ───────────────────────────────────────────────────
def _p(name, font="Helvetica", size=9, color=GRAY_900, align=TA_LEFT,
       leading=None, bold=False):
    return ParagraphStyle(
        name,
        fontName="Helvetica-Bold" if bold else font,
        fontSize=size,
        textColor=color,
        alignment=align,
        leading=leading or size * 1.35,
    )


def _styles():
    return {
        "SectionHead": _p("SH",  bold=True, size=9,  color=GREEN_DARK),
        "KV_Key":      _p("KVK", bold=True, size=9,  color=GREEN_DARK),
        "KV_Val":      _p("KVV", size=9,  color=GRAY_900),
        "TH":          _p("TH",  bold=True, size=8,  color=WHITE,   align=TA_CENTER),
        "TD":          _p("TD",  size=8,  color=GRAY_900),
        "TD_C":        _p("TDC", size=8,  color=GRAY_900, align=TA_CENTER),
        "Small":       _p("Sm",  size=8,  color=GRAY_500, leading=12),
        "Center":      _p("Ctr", size=8,  color=GRAY_500, align=TA_CENTER),
        "Bold":        _p("Bld", bold=True, size=9, color=GRAY_900),
        "GreenBold":   _p("GB",  bold=True, size=10, color=GREEN_DARK),
        "Sub":         _p("Sub", size=9, color=GRAY_500),
        # Payroll amounts
        "Amount":      _p("Amt", bold=True, size=10, color=GRAY_900, align=TA_RIGHT),
        "AmountNet":   _p("AN",  bold=True, size=11, color=GREEN_DARK, align=TA_RIGHT),
    }


# ── Canvas page decorator (banner + footer on every page) ─────────────────────
def _page_decorator(canvas, doc, title, subtitle):
    canvas.saveState()

    lx = MARGIN
    w  = BODY_W

    # ── Banner ─────────────────────────────────────────────────────────────
    by = PAGE_H - MARGIN - BANNER_H
    canvas.setFillColor(GREEN)
    canvas.roundRect(lx, by, w, BANNER_H, 6, fill=1, stroke=0)

    # accent stripe along the bottom of the banner
    canvas.setFillColor(GREEN_DARK)
    canvas.rect(lx, by, w, 3, fill=1, stroke=0)

    # Left: brand name
    canvas.setFont("Helvetica-Bold", 17)
    canvas.setFillColor(WHITE)
    canvas.drawString(lx + 14, by + BANNER_H * 0.55, "ApexForge")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(GREEN_ACCENT)
    canvas.drawString(lx + 14, by + BANNER_H * 0.2, "Sports Management Platform")

    # Right: document title + subtitle
    canvas.setFont("Helvetica-Bold", 12)
    canvas.setFillColor(WHITE)
    canvas.drawRightString(lx + w - 14, by + BANNER_H * 0.55, title)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(GREEN_ACCENT)
    canvas.drawRightString(lx + w - 14, by + BANNER_H * 0.2, subtitle)

    # ── Footer ──────────────────────────────────────────────────────────────
    fy = MARGIN - 0.3 * cm
    fh = 0.55 * cm
    canvas.setFillColor(GRAY_50)
    canvas.rect(lx, fy, w, fh, fill=1, stroke=0)
    canvas.setStrokeColor(GRAY_200)
    canvas.setLineWidth(0.5)
    canvas.line(lx, fy + fh, lx + w, fy + fh)

    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(GRAY_500)
    today = date.today().strftime("%d %B %Y")
    canvas.drawString(lx + 6, fy + 0.15 * cm, f"Generated by ApexForge  |  {today}")
    canvas.setFont("Helvetica-Bold", 7.5)
    canvas.drawRightString(lx + w - 6, fy + 0.15 * cm, f"Page {doc.page}")

    canvas.restoreState()


# ── Section heading ───────────────────────────────────────────────────────────
def _section(story, s, text):
    tbl = Table(
        [[Paragraph(text.upper(), s["SectionHead"])]],
        colWidths=[BODY_W],
    )
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), GREEN_LIGHT),
        ("LINEBEFORE",    (0, 0), (0, -1),  3, GREEN),
        ("LINEBELOW",     (0, 0), (-1, -1), 0.5, GRAY_200),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(Spacer(1, 0.3 * cm))
    story.append(tbl)
    story.append(Spacer(1, 0.15 * cm))


# ── KV info table ─────────────────────────────────────────────────────────────
def _kv_table(data, key_w=5 * cm, total_w=None):
    total_w = total_w or BODY_W
    val_w   = total_w - key_w
    rows = [
        [Paragraph(str(k), _p("k", bold=True, size=9, color=GREEN_DARK)),
         Paragraph(str(v), _p("v", size=9, color=GRAY_900))]
        for k, v in data
    ]
    tbl = Table(rows, colWidths=[key_w, val_w])
    tbl.setStyle(TableStyle([
        ("BACKGROUND",     (0, 0), (0, -1),  GREEN_LIGHT),
        ("ROWBACKGROUNDS", (1, 0), (1, -1),  [WHITE, GRAY_50]),
        ("GRID",           (0, 0), (-1, -1), 0.4, GRAY_200),
        ("LEFTPADDING",    (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",   (0, 0), (-1, -1), 8),
        ("TOPPADDING",     (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 6),
        ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
        ("LINEBELOW",      (0, -1), (-1, -1), 1, GREEN),
    ]))
    return tbl


# ── Data table ────────────────────────────────────────────────────────────────
def _data_table(headers, rows, col_widths=None, center_cols=None):
    center_cols = center_cols or []
    hdr_style = _p("_th", bold=True, size=8, color=WHITE,   align=TA_CENTER)
    bod_style  = _p("_td", size=8,  color=GRAY_900)
    bod_c      = _p("_tdc", size=8, color=GRAY_900, align=TA_CENTER)

    data = [[Paragraph(h, hdr_style) for h in headers]]
    for row in rows:
        data.append([
            Paragraph(str(c), bod_c if i in center_cols else bod_style)
            for i, c in enumerate(row)
        ])

    tbl = Table(data, colWidths=col_widths, repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND",     (0, 0),  (-1, 0),  GREEN),
        ("TOPPADDING",     (0, 0),  (-1, 0),  7),
        ("BOTTOMPADDING",  (0, 0),  (-1, 0),  7),
        ("ROWBACKGROUNDS", (0, 1),  (-1, -1), [WHITE, GRAY_50]),
        ("GRID",           (0, 0),  (-1, -1), 0.4, GRAY_200),
        ("LEFTPADDING",    (0, 0),  (-1, -1), 8),
        ("RIGHTPADDING",   (0, 0),  (-1, -1), 8),
        ("TOPPADDING",     (0, 1),  (-1, -1), 5),
        ("BOTTOMPADDING",  (0, 1),  (-1, -1), 5),
        ("VALIGN",         (0, 0),  (-1, -1), "MIDDLE"),
        ("LINEBELOW",      (0, -1), (-1, -1), 1, GREEN),
    ]))
    return tbl


# ── Stat badge (colored background cell) ─────────────────────────────────────
def _badge_cell(tbl, col, row, bg, fg):
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (col, row), (col, row), bg),
        ("TEXTCOLOR",  (col, row), (col, row), fg),
        ("FONTNAME",   (col, row), (col, row), "Helvetica-Bold"),
    ]))


def _pdf_response(filename):
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = f'attachment; filename="{filename}"'
    return response


# ═══════════════════════════════════════════════════════════════════════════════
# 1. Player Profile PDF
# ═══════════════════════════════════════════════════════════════════════════════

def player_profile_pdf(player):
    fname = f"player_{player.pk}_{player.full_name.replace(' ', '_')}.pdf"
    response = _pdf_response(fname)
    buf = io.BytesIO()

    doc_title    = player.full_name
    doc_subtitle = f"Player Profile  |  {player.get_sport_display()}"

    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=TOP_MARGIN, bottomMargin=BOT_MARGIN,
    )
    s = _styles()
    story = []

    # ── Bio (2-column grid) ──────────────────────────────────────────────────
    _section(story, s, "Player Information")
    dob  = player.date_of_birth
    half = (BODY_W - 0.3 * cm) / 2
    kw   = 3.6 * cm

    left_tbl  = _kv_table([
        ("Full Name",   player.full_name),
        ("Position",    player.position or "—"),
        ("Sport",       player.get_sport_display()),
        ("Nationality", player.nationality or "—"),
    ], key_w=kw, total_w=half)

    right_tbl = _kv_table([
        ("Date of Birth", str(dob) if dob else "—"),
        ("Status",        player.get_status_display()),
        ("Height",        f"{player.height_cm} cm" if player.height_cm else "—"),
        ("Weight",        f"{player.weight_kg} kg" if player.weight_kg else "—"),
    ], key_w=kw, total_w=half)

    grid = Table(
        [[left_tbl, "", right_tbl]],
        colWidths=[half, 0.3 * cm, half],
    )
    grid.setStyle(TableStyle([
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING",   (1, 0), (1, -1), 0),
        ("RIGHTPADDING",  (1, 0), (1, -1), 0),
        ("TOPPADDING",    (1, 0), (1, -1), 0),
        ("BOTTOMPADDING", (1, 0), (1, -1), 0),
    ]))
    story.append(grid)

    # ── Current team ─────────────────────────────────────────────────────────
    roster = player.rosters.select_related("team", "season").filter(is_active=True).first()
    if roster:
        _section(story, s, "Current Team")
        story.append(KeepTogether(_kv_table([
            ("Team",     roster.team.name),
            ("Season",   str(roster.season) if roster.season else "—"),
            ("Jersey",   f"#{roster.jersey_number}" if roster.jersey_number else "—"),
            ("Position", roster.position or "—"),
            ("Captain",  "Yes" if roster.is_captain else "No"),
        ])))

    # ── Season stats ──────────────────────────────────────────────────────────
    stats = player.stats.select_related("season", "team").order_by("-season__start_date")[:6]
    if stats:
        _section(story, s, "Season Statistics")
        rows = [[
            str(st.season) if st.season else "—",
            st.team.name if st.team else "—",
            str(st.goals),
            str(st.assists),
            str(st.appearances),
            str(st.yellow_cards),
            str(st.red_cards),
        ] for st in stats]

        tbl = _data_table(
            ["Season", "Team", "Goals", "Assists", "Apps", "Yellow", "Red"],
            rows,
            col_widths=[3.2*cm, 4.4*cm, 1.9*cm, 2*cm, 1.9*cm, 2.2*cm, 2.3*cm],
            center_cols=[2, 3, 4, 5, 6],
        )
        for i, st in enumerate(stats, 1):
            if st.yellow_cards:
                _badge_cell(tbl, 5, i, AMBER_BG, AMBER_FG)
            if st.red_cards:
                _badge_cell(tbl, 6, i, RED_BG, RED_FG)
            if st.goals >= 10:
                _badge_cell(tbl, 2, i, GREEN_LIGHT, GREEN_DARK)

        story.append(tbl)

    # ── Injury history ────────────────────────────────────────────────────────
    injuries = player.injuries.order_by("-injury_date")[:5]
    if injuries:
        _section(story, s, "Injury History")
        sev_colors = {
            "minor":    (colors.HexColor("#dcfce7"), colors.HexColor("#166534")),
            "moderate": (AMBER_BG, AMBER_FG),
            "severe":   (RED_BG,   RED_FG),
        }
        rows = [[
            str(inj.injury_date),
            inj.injury_type,
            inj.body_part or "—",
            inj.get_severity_display(),
            str(inj.expected_return) if inj.expected_return else "—",
        ] for inj in injuries]

        tbl = _data_table(
            ["Date", "Type", "Body Part", "Severity", "Expected Return"],
            rows,
            col_widths=[2.8*cm, 4.2*cm, 3.5*cm, 3.2*cm, 4.2*cm],
            center_cols=[0, 3, 4],
        )
        for i, inj in enumerate(injuries, 1):
            bg, fg = sev_colors.get(inj.severity, (WHITE, GRAY_900))
            tbl.setStyle(TableStyle([
                ("BACKGROUND", (3, i), (3, i), bg),
                ("TEXTCOLOR",  (3, i), (3, i), fg),
                ("FONTNAME",   (3, i), (3, i), "Helvetica-Bold"),
            ]))
        story.append(tbl)

    cb = lambda c, d: _page_decorator(c, d, doc_title, doc_subtitle)
    doc.build(story, onFirstPage=cb, onLaterPages=cb)
    response.write(buf.getvalue())
    return response


# ═══════════════════════════════════════════════════════════════════════════════
# 2. Contract PDF
# ═══════════════════════════════════════════════════════════════════════════════

def contract_pdf(contract):
    fname = f"contract_{contract.pk}_{contract.title.replace(' ', '_')}.pdf"
    response = _pdf_response(fname)
    buf = io.BytesIO()

    doc_title    = contract.title
    doc_subtitle = f"Contract  |  {contract.get_contract_type_display()}"

    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=TOP_MARGIN, bottomMargin=BOT_MARGIN,
    )
    s = _styles()
    story = []

    # ── Contract details ──────────────────────────────────────────────────────
    _section(story, s, "Contract Details")
    days_rem = getattr(contract, "days_remaining", None)
    status_display = contract.get_status_display()
    story.append(_kv_table([
        ("Contract Type",  contract.get_contract_type_display()),
        ("Status",         status_display),
        ("Party",          getattr(contract, "party_name", "—") or "—"),
        ("Start Date",     str(contract.start_date)),
        ("End Date",       str(contract.end_date)),
        ("Value",          f"€ {contract.value:,.2f}" if contract.value else "—"),
        ("Days Remaining", f"{days_rem} days" if days_rem and days_rem > 0 else "Expired"),
        ("Signed",         "Yes" if contract.signed_date else "No"),
        ("Signed Date",    str(contract.signed_date) if contract.signed_date else "—"),
    ]))

    # ── Notes ─────────────────────────────────────────────────────────────────
    if contract.notes:
        _section(story, s, "Notes")
        story.append(Paragraph(contract.notes, s["Small"]))

    # ── Clauses ───────────────────────────────────────────────────────────────
    clauses = contract.clauses.all()
    if clauses:
        _section(story, s, "Contract Clauses")
        rows = [
            [c.get_clause_type_display(), c.title,
             c.description[:90] + ("…" if len(c.description) > 90 else "")]
            for c in clauses
        ]
        story.append(_data_table(
            ["Type", "Title", "Description"],
            rows,
            col_widths=[4 * cm, 4.5 * cm, 9.4 * cm],
        ))

    # ── Signature block ───────────────────────────────────────────────────────
    story.append(Spacer(1, 1.2 * cm))
    _section(story, s, "Signatures")
    story.append(Spacer(1, 0.8 * cm))
    sig = Table(
        [
            ["Authorised Signatory", "", "Witness / Counterparty"],
            [" ", "", " "],
            [" ", "", " "],
            ["_________________________", "", "_________________________"],
            ["Name & Title", "", "Name & Title"],
            [f"Date: {'_' * 20}", "", f"Date: {'_' * 20}"],
        ],
        colWidths=[7.5 * cm, 2.9 * cm, 7.5 * cm],
    )
    sig.setStyle(TableStyle([
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  GREEN_DARK),
        ("TEXTCOLOR",     (0, 1), (-1, -1), GRAY_500),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW",     (0, 2), (0, 2),   0.75, GRAY_500),
        ("LINEBELOW",     (2, 2), (2, 2),   0.75, GRAY_500),
    ]))
    story.append(sig)

    cb = lambda c, d: _page_decorator(c, d, doc_title, doc_subtitle)
    doc.build(story, onFirstPage=cb, onLaterPages=cb)
    response.write(buf.getvalue())
    return response


# ═══════════════════════════════════════════════════════════════════════════════
# 3. Payroll Slip PDF
# ═══════════════════════════════════════════════════════════════════════════════

def payroll_slip_pdf(payroll):
    name = payroll.staff_member.user.get_full_name()
    fname = f"payroll_{payroll.pk}_{name.replace(' ', '_')}.pdf"
    response = _pdf_response(fname)
    buf = io.BytesIO()

    if getattr(payroll, "period_start", None):
        period = (f"{payroll.period_start.strftime('%d %b')} – "
                  f"{payroll.period_end.strftime('%d %b %Y')}")
    else:
        period = "—"

    doc_title    = "Payroll Slip"
    doc_subtitle = f"{name}  |  {period}"

    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=TOP_MARGIN, bottomMargin=BOT_MARGIN,
    )
    s = _styles()
    story = []

    # ── Employee info ─────────────────────────────────────────────────────────
    _section(story, s, "Employee Information")
    half = (BODY_W - 0.3 * cm) / 2
    kw   = 3.6 * cm

    left_tbl = _kv_table([
        ("Employee",   name),
        ("Job Title",  payroll.staff_member.job_title or "—"),
        ("Department", str(payroll.staff_member.department)
                       if payroll.staff_member.department else "—"),
    ], key_w=kw, total_w=half)

    right_tbl = _kv_table([
        ("Period",  period),
        ("Status",  "Paid" if getattr(payroll, "is_paid", False) else "Pending"),
        ("Notes",   payroll.notes or "—"),
    ], key_w=kw, total_w=half)

    grid = Table(
        [[left_tbl, "", right_tbl]],
        colWidths=[half, 0.3 * cm, half],
    )
    grid.setStyle(TableStyle([
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING",   (1, 0), (1, -1), 0),
        ("RIGHTPADDING",  (1, 0), (1, -1), 0),
        ("TOPPADDING",    (1, 0), (1, -1), 0),
        ("BOTTOMPADDING", (1, 0), (1, -1), 0),
    ]))
    story.append(grid)

    # ── Earnings & deductions ─────────────────────────────────────────────────
    _section(story, s, "Earnings & Deductions")

    earn_rows = [
        # label, description, amount style, amount
        ("Gross Salary",  "Base remuneration",               "normal", payroll.gross_salary),
        ("Bonuses",       "Additional performance bonuses",  "normal", payroll.bonuses),
        ("Deductions",    "Tax, insurance & other",          "deduct", payroll.deductions),
    ]

    tbl_data = [
        [Paragraph("Description",   _p("_", bold=True, size=9, color=WHITE)),
         Paragraph("Details",       _p("_", bold=True, size=9, color=WHITE)),
         Paragraph("Amount",        _p("_", bold=True, size=9, color=WHITE, align=TA_RIGHT))],
    ]
    for label, detail, kind, amount in earn_rows:
        sign   = "-€" if kind == "deduct" else " €"
        fg     = RED_FG if kind == "deduct" else GRAY_900
        tbl_data.append([
            Paragraph(label,  _p("_", bold=True,  size=9,  color=GRAY_700)),
            Paragraph(detail, _p("_", size=9, color=GRAY_500)),
            Paragraph(f"{sign}{amount:,.2f}", _p("_", bold=True, size=9, color=fg, align=TA_RIGHT)),
        ])

    # Net row
    tbl_data.append([
        Paragraph("NET SALARY", _p("_", bold=True, size=11, color=GREEN_DARK)),
        Paragraph("", _p("_", size=9, color=WHITE)),
        Paragraph(f"€ {payroll.net_salary:,.2f}",
                  _p("_", bold=True, size=11, color=GREEN_DARK, align=TA_RIGHT)),
    ])

    earn_tbl = Table(tbl_data, colWidths=[5.5 * cm, 8.5 * cm, 3.9 * cm])
    earn_tbl.setStyle(TableStyle([
        # Header
        ("BACKGROUND",    (0, 0), (-1, 0),  GREEN),
        ("TOPPADDING",    (0, 0), (-1, 0),  8),
        ("BOTTOMPADDING", (0, 0), (-1, 0),  8),
        # Body rows
        ("ROWBACKGROUNDS",(0, 1), (-1, -2), [WHITE, GRAY_50]),
        ("GRID",          (0, 0), (-1, -2), 0.4, GRAY_200),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
        ("TOPPADDING",    (0, 1), (-1, -2), 7),
        ("BOTTOMPADDING", (0, 1), (-1, -2), 7),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        # Net salary row
        ("BACKGROUND",    (0, -1), (-1, -1), GREEN_LIGHT),
        ("LINEABOVE",     (0, -1), (-1, -1), 1.5, GREEN),
        ("LINEBELOW",     (0, -1), (-1, -1), 1.5, GREEN),
        ("TOPPADDING",    (0, -1), (-1, -1), 10),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 10),
    ]))
    story.append(earn_tbl)

    # ── Official notice ───────────────────────────────────────────────────────
    story.append(Spacer(1, 0.8 * cm))
    notice = Table(
        [[Paragraph(
            "This document is an official payroll record issued by ApexForge. "
            "Please retain for your records.",
            _p("_", size=8, color=GRAY_500, align=TA_CENTER),
        )]],
        colWidths=[BODY_W],
    )
    notice.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), GRAY_50),
        ("LINEABOVE",     (0, 0), (-1, -1), 0.5, GRAY_200),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
    ]))
    story.append(notice)

    cb = lambda c, d: _page_decorator(c, d, doc_title, doc_subtitle)
    doc.build(story, onFirstPage=cb, onLaterPages=cb)
    response.write(buf.getvalue())
    return response
