# Generated by Django 5.1.15 on 2026-04-25 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age_group', models.CharField(choices=[('u8', 'Under 8'), ('u10', 'Under 10'), ('u12', 'Under 12'), ('u14', 'Under 14'), ('u16', 'Under 16'), ('u18', 'Under 18'), ('u21', 'Under 21'), ('senior', 'Senior')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_players', models.PositiveSmallIntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
                ('goals', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_programs', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_programs', to='teams.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(help_text='e.g. 2024-25', max_length=20)),
                ('goals', models.TextField()),
                ('strengths', models.TextField(blank=True)),
                ('areas_to_improve', models.TextField(blank=True)),
                ('technical_rating', models.PositiveSmallIntegerField(default=5)),
                ('tactical_rating', models.PositiveSmallIntegerField(default=5)),
                ('physical_rating', models.PositiveSmallIntegerField(default=5)),
                ('mental_rating', models.PositiveSmallIntegerField(default=5)),
                ('overall_rating', models.PositiveSmallIntegerField(default=5)),
                ('coach_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dev_plans', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to='players.player')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to='academy.academyprogram')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('player', 'program', 'season')},
            },
        ),
        migrations.CreateModel(
            name='DevelopmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('achieved', models.BooleanField(default=False)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='academy.developmentplan')),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
    ]
