# Generated by Django 5.1.15 on 2026-04-25 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('second_nationality', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('secondary_position', models.CharField(blank=True, max_length=50)),
                ('preferred_foot', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], default='right', max_length=10)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height (cm)')),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('injured', 'Injured'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('transfer', 'Transfer Listed')], default='active', max_length=20)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('contract_until', models.DateField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('rugby', 'Rugby'), ('baseball', 'Baseball'), ('volleyball', 'Volleyball'), ('hockey', 'Hockey'), ('swimming', 'Swimming'), ('athletics', 'Athletics'), ('cycling', 'Cycling'), ('other', 'Other')], default='football', max_length=30)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='players.player')),
            ],
            options={
                'verbose_name': 'performance metric',
                'verbose_name_plural': 'performance metrics',
                'ordering': ['-date', 'metric'],
            },
        ),
        migrations.CreateModel(
            name='InjuryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=200)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='minor', max_length=20)),
                ('injury_date', models.DateField()),
                ('expected_return', models.DateField(blank=True, null=True)),
                ('actual_return', models.DateField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injury_records', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='players.player')),
            ],
            options={
                'verbose_name': 'injury log',
                'verbose_name_plural': 'injury logs',
                'ordering': ['-injury_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearances', models.PositiveSmallIntegerField(default=0)),
                ('starts', models.PositiveSmallIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('shots', models.PositiveSmallIntegerField(default=0)),
                ('shots_on_target', models.PositiveSmallIntegerField(default=0)),
                ('passes', models.PositiveIntegerField(default=0)),
                ('pass_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tackles', models.PositiveSmallIntegerField(default=0)),
                ('interceptions', models.PositiveSmallIntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.player')),
            ],
            options={
                'verbose_name': 'player stats',
                'verbose_name_plural': 'player stats',
                'ordering': ['-season__start_date'],
            },
        ),
    ]
