# Generated by Django 5.1.15 on 2026-04-25 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.season'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='teams.team'),
        ),
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together={('player', 'team', 'season')},
        ),
    ]
